"""Constants for the MeteoLux integration."""
from datetime import time
from typing import Final

DOMAIN = "meteolux"

CONF_FORECAST_DAYS: Final = "forecast_days"
DEFAULT_FORECAST_DAYS: Final = 5
FORECAST_DAYS_RANGE: Final = list(range(1, 6))

# Old CSV data source (kept as fallback)
DATA_URL = "https://data.public.lu/en/datasets/r/c05ecc27-aa44-4c96-bece-6149783e1758"

# New MeteoLux API endpoints
API_BASE_URL = "https://metapi.ana.lu/api/v1"
WEATHER_ENDPOINT = f"{API_BASE_URL}/weather"
METAPP_WEATHER_ENDPOINT = f"{API_BASE_URL}/metapp/weather"

CONDITION_MAP = {
    # English conditions
    "Clear sky": "sunny",
    "Clear": "sunny", 
    "Sunny": "sunny",
    "Partly cloudy": "partlycloudy",
    "Partly Cloudy": "partlycloudy",
    "Few clouds": "partlycloudy",
    "Scattered clouds": "partlycloudy",
    "Broken clouds": "cloudy",
    "Cloudy": "cloudy",
    "Overcast": "cloudy",
    "Overcast clouds": "cloudy",
    "Light rain": "rainy",
    "Light Rain": "rainy",
    "Moderate rain": "rainy",
    "Moderate Rain": "rainy",
    "Heavy rain": "pouring",
    "Heavy Rain": "pouring",
    "Heavy intensity rain": "pouring",
    "Very heavy rain": "pouring",
    "Extreme rain": "pouring",
    "Rain": "rainy",
    "Light intensity shower rain": "rainy",
    "Shower rain": "rainy",
    "Heavy intensity shower rain": "pouring",
    "Ragged shower rain": "rainy",
    "Drizzle": "rainy",
    "Light intensity drizzle": "rainy",
    "Heavy intensity drizzle": "rainy",
    "Light drizzle": "rainy",
    "Fog": "fog",
    "Mist": "fog",
    "Smoke": "fog",
    "Haze": "fog",
    "Sand/dust whirls": "fog",
    "Dust": "fog",
    "Volcanic ash": "fog",
    "Squalls": "windy",
    "Tornado": "exceptional",
    "Snow": "snowy",
    "Light snow": "snowy",
    "Heavy snow": "snowy",
    "Sleet": "snowy",
    "Light shower sleet": "snowy",
    "Shower sleet": "snowy",
    "Light rain and snow": "snowy",
    "Rain and snow": "snowy",
    "Light shower snow": "snowy",
    "Shower snow": "snowy",
    "Heavy shower snow": "snowy",
    "Thunderstorm": "lightning",
    "Thunderstorm with light rain": "lightning-rainy",
    "Thunderstorm with rain": "lightning-rainy",
    "Thunderstorm with heavy rain": "lightning-rainy",
    "Light thunderstorm": "lightning",
    "Heavy thunderstorm": "lightning",
    "Ragged thunderstorm": "lightning",
    "Thunderstorm with light drizzle": "lightning-rainy",
    "Thunderstorm with drizzle": "lightning-rainy",
    "Thunderstorm with heavy drizzle": "lightning-rainy",
    # Generic fallbacks
    "Rainy": "rainy",
    "Snowy": "snowy",
    "Cloudy": "cloudy",
    # French conditions
    "Ciel dégagé": "sunny",
    "Ciel clair": "sunny",
    "Ensoleillé": "sunny",
    "Partiellement nuageux": "partlycloudy",
    "Quelques nuages": "partlycloudy",
    "Nuages épars": "partlycloudy",
    "Nuages fragmentés": "cloudy",
    "Nuageux": "cloudy",
    "Couvert": "cloudy",
    "Nuages couverts": "cloudy",
    "Pluie faible": "rainy",
    "Pluie légère": "rainy",
    "Pluie modérée": "rainy",
    "Pluie forte": "pouring",
    "Pluie intense": "pouring",
    "Pluie très forte": "pouring",
    "Pluie extrême": "pouring",
    "Pluie": "rainy",
    "Averse légère": "rainy",
    "Averse": "rainy",
    "Averse forte": "pouring",
    "Averse irrégulière": "rainy",
    "Bruine": "rainy",
    "Bruine légère": "rainy",
    "Bruine forte": "rainy",
    "Brouillard": "fog",
    "Brume": "fog",
    "Fumée": "fog",
    "Voile": "fog",
    "Tourbillons de sable/poussière": "fog",
    "Poussière": "fog",
    "Cendres volcaniques": "fog",
    "Bourrasques": "windy",
    "Tornade": "exceptional",
    "Neige": "snowy",
    "Neige légère": "snowy",
    "Neige forte": "snowy",
    "Neige fondue": "snowy",
    "Averse de neige fondue légère": "snowy",
    "Averse de neige fondue": "snowy",
    "Pluie et neige légère": "snowy",
    "Pluie et neige": "snowy",
    "Averse de neige légère": "snowy",
    "Averse de neige": "snowy",
    "Averse de neige forte": "snowy",
    "Orage": "lightning",
    "Orage avec pluie légère": "lightning-rainy",
    "Orage avec pluie": "lightning-rainy",
    "Orage avec pluie forte": "lightning-rainy",
    "Orage léger": "lightning",
    "Orage fort": "lightning",
    "Orage irrégulier": "lightning",
    "Orage avec bruine légère": "lightning-rainy",
    "Orage avec bruine": "lightning-rainy",
    "Orage avec bruine forte": "lightning-rainy",
}

FORECAST_TIMES = {
    "morning": time(8, 0, 0),
    "afternoon": time(14, 0, 0),
    "evening": time(20, 0, 0),
}
